### ISSUE TITLE
logconfig elasticsearch报错

### ISSUE THREAD

**Issue by EverCurse** [loggie-io/loggie#114]
{"level":"warn","time":"2022-03-21T17:26:04Z","caller":"/go/src/loggie.io/loggie/pkg/interceptor/retry/interceptor.go:175","message":"interceptor/retry retry buffer size(2) too large"}
{"level":"error","time":"2022-03-21T17:26:04Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:267","message":"consumer batch fail,err: elasticsearch client not initialized yet"}

es版本7x

**Comment by ethfoo** [comment]
看起来是连接环境里的es有问题。

有没有更多的报错日志信息？
pipeline配置也麻烦脱敏后发一下

**Comment by EverCurse** [comment]
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"loggie.io/v1beta1","kind":"Sink","metadata":{"annotations":{},"name":"default"},"spec":{"sink":"type: elasticsearch\nindex: \"loggie\"\nhosts: [\"192.168.18.131:9200\"]\n"}}
  creationTimestamp: "2022-03-21T17:48:13Z"
  generation: 5
  name: default
  resourceVersion: "1897599"
  uid: d13c1f62-2cf8-48ab-8425-db271c74cec4
spec:
  sink: |
    type: dev
    printEvents: true
    parallelism: 100


apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"loggie.io/v1beta1","kind":"LogConfig","metadata":{"annotations":{},"creationTimestamp":"2022-03-21T16:30:55Z","generation":1,"name":"fates-1","namespace":"default","resourceVersion":"1883375","uid":"c7f48437-2a6f-4576-aad9-ecc25091de7a"},"spec":{"pipeline":{"interceptorRef":"default","sinkRef":"default","sources":"- type: file\n  name: common\n  paths:\n    - stdout\n    - /data/logs/*\n"},"selector":{"labelSelector":{"app":"xxx"},"type":"pod"}}}
  creationTimestamp: "2022-03-21T17:12:42Z"
  generation: 11
  name: fates-1
  namespace: default
  resourceVersion: "1897475"
  uid: 66cd6766-ee64-497b-bce0-34a828e6312f
spec:
  pipeline:
    sinkRef: default
    sources: |
      - type: file
        name: common
        paths:
          - /logs/*.log
  selector:
    labelSelector:
      app: xxxx
    type: pod

**Comment by EverCurse** [comment]
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  generation: 5
  name: default
  resourceVersion: "1897599"
  uid: d13c1f62-2cf8-48ab-8425-db271c74cec4
spec:
  sink: |
    type: elasticsearch
    index: loggie
    hosts: ["192.168.18.131:9200"]


apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  creationTimestamp: "2022-03-21T17:12:42Z"
  generation: 11
  name: fates-1
  namespace: default
  resourceVersion: "1897475"
  uid: 66cd6766-ee64-497b-bce0-34a828e6312f
spec:
  pipeline:
    sinkRef: default
    sources: |
      - type: file
        name: common
        paths:
          - /logs/*.log
  selector:
    labelSelector:
      app: xxxx
    type: pod

**Comment by EverCurse** [comment]
`apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  generation: 5
  name: default
  resourceVersion: "1897599"
  uid: d13c1f62-2cf8-48ab-8425-db271c74cec4
spec:
  sink: |
    type: elasticsearch
    index: loggie
    hosts: ["192.168.18.131:9200"]


apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  creationTimestamp: "2022-03-21T17:12:42Z"
  generation: 11
  name: fates-1
  namespace: default
  resourceVersion: "1897475"
  uid: 66cd6766-ee64-497b-bce0-34a828e6312f
spec:
  pipeline:
    sinkRef: default
    sources: |
      - type: file
        name: common
        paths:
          - /logs/*.log
  selector:
    labelSelector:
      app: xxxx
    type: pod`

**Comment by EverCurse** [comment]
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  generation: 5
  name: default
  resourceVersion: "1897599"
  uid: d13c1f62-2cf8-48ab-8425-db271c74cec4
spec:
  sink: |
    type: elasticsearch
    index: loggie
    hosts: ["192.168.18.131:9200"]


apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  creationTimestamp: "2022-03-21T17:12:42Z"
  generation: 11
  name: fates-1
  namespace: default
  resourceVersion: "1897475"
  uid: 66cd6766-ee64-497b-bce0-34a828e6312f
spec:
  pipeline:
    sinkRef: default
    sources: |
      - type: file
        name: common
        paths:
          - /logs/*.log
  selector:
    labelSelector:
      app: xxxx
    type: pod

**Comment by EverCurse** [comment]
@ethfoo  我的es是docker启动的 -p 暴露出来的端口

**Comment by EverCurse** [comment]
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/queue/channel/queue.go:83","message":"sinCount: 1"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/queue/channel/queue.go:84","message":"queue/channel batch size: 2048"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/queue/channel/queue.go:96","message":"queue listeners: file-source-ack-listener-wallet-group-1-fates-1-5fd54db9fb-759r8/xxxxx/common "}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:463","message":"sink interceptor chain: queue->interceptor/retry->interceptor/metric->sink"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:461","message":"retry interceptor chain: queue->interceptor/retry->interceptor/metric->sink"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:606","message":"source wallet-group-1-fates-1-5fd54db9fb-759r8/wallet-group-1-fates-1/common interceptor chain: source->interceptor/maxbytes->queue"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:202","message":"pipeline start with epoch: default/fates-1:1:2022-03-22 07:07:44"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/persistence.go:165","message":"registry db start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/ack.go:287","message":"ack chain handler start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/queue/channel/queue.go:102","message":"channel queue worker start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/watch.go:599","message":"watcher start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/read.go:107","message":"read worker-0 start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/pipeline/pipeline.go:412","message":"pipeline sink(sink/elasticsearch)-0 invoke loop start"}
{"level":"info","time":"2022-03-22T07:07:50Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/source.go:159","message":"source/file/xxxx-5fd54db9fb-759r8/xxxx-fates-1/common start product loop"}
{"level":"info","time":"2022-03-22T07:08:00Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/watch.go:309","message":"[default/xxxx-1-5fd54db9fb-759r8/wallet-group-1-fates-1/common] start collect file: /var/lib/kubelet/pods/60f4bd54-fca2-4c73-9e25-917392e77f13/volumes/kubernetes.io~empty-dir/log/1.log"}

**Comment by OliverWoo** [comment]
@EverCurse es sink sniff选项设置为false试下，之前遇到了开启sniff时和es建立连接失败

**Comment by EverCurse** [comment]
@OliverWoo  spec:
  sink: |
    name: fates
    type: elasticsearch
    index: loggie
    hosts: ["192.168.18.131:9200"]
    sniff: false

貌似还是不行 我看看日志 这个config是动态的吧

**Comment by EverCurse** [comment]
@OliverWoo @ethfoo 成功了 我看index有了
