### ISSUE TITLE
k8s stdout 日志 source多行合并

### ISSUE THREAD

**Issue by salman0927** [loggie-io/loggie#134]
pod 的stdout日志是json格式，例如：{"log":"01-Dec-2021 03:13:58.298 INFO [main] Starting service","stream":"stdout","time":"2021-06-02T03:20:54.260571439Z"}。如果是java的堆栈报错日子，需要根据正则多行合并成一条日志，有什么方法吗？

**Comment by mmaxiaolei** [comment]
合并多行后，希望保持json的结构吗？另外，合并多行，json的其他属性期望是保留首行的属性还是末行的属性呢？

**Comment by ethfoo** [comment]
Fixed: https://github.com/loggie-io/loggie/pull/239
release v1.2.0
