### ISSUE TITLE
【help】最新日志无法收集

### ISSUE THREAD

**Issue by EverCurse** [loggie-io/loggie#135]
最新日志无法收集  详情请见 https://app.yinxiang.com/fx/4a475f8e-185f-4722-88fe-da8fdacab2cf

重启daemonset的loggie pod会瞬间收集一波 然后最新日志就不更新了

**Comment by ethfoo** [comment]
麻烦贴一下loggie的日志

**Comment by EverCurse** [comment]
@ethfoo 
{"level":"info","time":"2022-04-03T13:37:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:38:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:38:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:39:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:39:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:40:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:40:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:41:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:41:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:42:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"filewatcher\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}



{"level":"info","time":"2022-04-03T13:42:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:43:06Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}
{"level":"info","time":"2022-04-03T13:43:36Z","caller":"/go/src/loggie.io/loggie/pkg/eventbus/export/logger/logger.go:141","message":"[metric]: {\"filesource\":{},\"reload\":{\"ReloadTotal\":1},\"sink\":{}}"}

**Comment by EverCurse** [comment]
在上述的日志之前有 类似这样的日志

{"level":"info","time":"2022-04-03T13:26:56Z","caller":"/go/src/loggie.io/loggie/pkg/source/file/watch.go:307","message":"[default/clotho-1-xxx-group-1-clotho-1-54bf8898d-qskgl/xxx-group-1-clotho-1/clotho-1] start collect file from existFileName(/var/lib/kubelet/pods/777a941d-23af-4f9a-8391-0f5ffe91637a/volumes/kubernetes.io~empty-dir/log/common-error.log) with existOffset(1928843): /var/lib/kubelet/pods/777a941d-23af-4f9a-8391-0f5ffe91637a/volumes/kubernetes.io~empty-dir/log/common-error.log"}

**Comment by ethfoo** [comment]
同时采集64个日志文件的bug已经在main分支修复，即将在v1.1.0 release
