### ISSUE TITLE
Static pod support

### ISSUE THREAD

**Issue by guanbear** [loggie-io/loggie#245]
## Describe the feature
loggie 可以支持静态pod吗？ 比如kubeadm 搭建的集群，如果想采集 kube-apiserver 或者etcd的日志，目前测试按pod来配置logconfig是采集不到的，估计和容器名的格式不一致有关，导致匹配不到。目前只能按照node方式配置，希望能支持静态pod。

**Comment by ethfoo** [comment]
static pod由于k8s会创建minor pod，k8s生成的stdout路径/var/log/pods/<namespace>_<pod_name>_<pod_id>/，这里不是pod_id。
如果你用的是docker，可以把系统配置discovery.kubernetes.containerRuntime改成docker，从/var/lib/docker/containers路径下采集stdout日志应该就没有这个问题

**Comment by guanbear** [comment]
好的，感谢，我用的是docker，我也试下你说的方案。

**Comment by listencx** [comment]
静态pod对应日志目录pid是pod注解中的kubernetes.io/config.hash。
可以修改pkg/discovery/kubernetes/helper/kube.go:162  实现采集静态pod
```
if path == logconfigv1beta1.PathStdout {
	staticPodHash, ok := pod.Annotations["kubernetes.io/config.hash"]
	if ok {
		nodePaths = append(nodePaths, GenContainerStdoutLog(podLogDirPrefix, pod.Namespace, pod.Name, staticPodHash, containerName)...)
	} else {
		nodePaths = append(nodePaths, GenContainerStdoutLog(podLogDirPrefix, pod.Namespace, pod.Name, string(pod.UID), containerName)...)
	}
	continue
}
```

**Comment by guanbear** [comment]
升级到1.30后已经支持了，这个关闭。
