### ISSUE TITLE
Lost "leases" resource in loggie-rbac.yaml

### ISSUE THREAD

**Issue by guanbear** [loggie-io/loggie#249]
## What version of Loggie?
1.1.0
## Expected Behavior
loggie-aggregator runs normally

## Actual Behavior
get error:
error retrieving resource lock kube-system/loggie-leader-election-key: leases.coordination.k8s.io "loggie-leader-election-key" is forbidden: User "system:serviceaccount:loggie-aggregator:loggie-aggregator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"

![image](https://user-images.githubusercontent.com/11829005/173035091-1a88f391-50d0-40cc-a864-817e0cbe0397.png)
![image](https://user-images.githubusercontent.com/11829005/173035110-b2c49fb9-b4b5-43f4-9ab5-39ae14193bf3.png)

## Steps to Reproduce the Problem

Add missing RBAC permissions to allow loggie-aggregator do its leader election

**Comment by guanbear** [comment]
我自己在 loggie-rbac.yaml 中已经修复了，我可以提个PR

**Comment by ethfoo** [comment]
> 我自己在 loggie-rbac.yaml 中已经修复了，我可以提个PR 参考：https://github.com/bitnami/charts/pull/7035/files

好的，麻烦提个PR

**Comment by guanbear** [comment]
> > 我自己在 loggie-rbac.yaml 中已经修复了，我可以提个PR 参考：https://github.com/bitnami/charts/pull/7035/files
> 
> 好的，麻烦提个PR

已提：https://github.com/loggie-io/installation/pull/18
