### ISSUE TITLE
希望loggie 对换行符配置支持

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [loggie-io/loggie#255]
loggie 现在file 模块行处理只支持\n，这支持不是很够，所以希望对多种换行符支持；
例如windows: \r\n
UTF-16:000D 000A
这些场景下loggie \n显得单薄，所以希望对loggie加入换行符支持
是否只需要在lineProcess加入处理就可以，主要集中修改在file的source模块就ok吗

**Comment by ethfoo** [comment]
released in v1.3.
