### ISSUE TITLE
基于Daemonset方式部署，是否只能获取容器的日志信息？

### ISSUE THREAD

**Issue by jackchen-2014** [loggie-io/loggie#262]
daemonset 方式配置的话，是否只能支持采集容器默认的日志？
如果希望采集到基于日志框架收集到的file日志，是不是只能通过sidecar方式？

**Comment by ethfoo** [comment]
除了采集标准输出外，可以采集容器内的日志文件。
请参考：https://loggie-io.github.io/docs/user-guide/use-in-kubernetes/collect-container-logs/#_3
logconfig中 file source填写容器内的日志文件path即可。（loggie会自动识别并转换成节点的日志文件路径，所以loggie会挂载节点的一些路径，因为loggie也是容器部署，需要看到节点上实际的日志文件）

**Comment by jackchen-2014** [comment]
> *
现有的服务没有可以统一的标识，这是不是就意味着得需要对现有的服务增加标签？

**Comment by ethfoo** [comment]
> > 
> 
> 现有的服务没有可以统一的标识，这是不是就意味着得需要对现有的服务增加标签？

如果不增加标签，可以使用logconfig 和 服务 一对一的形式，label具体是什么无所谓。
当然统一label更好。

**Comment by jackchen-2014** [comment]
> > > 
> > 
> > 
> > 现有的服务没有可以统一的标识，这是不是就意味着得需要对现有的服务增加标签？
> 
> 如果不增加标签，可以使用logconfig 和 服务 一对一的形式，label具体是什么无所谓。 当然统一label更好。

> 好的，感谢您的回复。 该项目 后面是否能够提供完整的example？两种采集方式的完整示例。
