### ISSUE TITLE
日志拆分之后，如何实现落到ES中得内容拆分？

### ISSUE THREAD

**Issue by jackchen-2014** [loggie-io/loggie#263]
基于sidecar的方式进行部署，
其中configmap的配置如下：
pipeline.yml: |
    pipelines:
      - name: "apm-engine"
        sources:
          - type: "file"
            name: "apm-engine-log"
            paths:
              - "/home/app/apm-engine-app/logs/*.log"
            fields:
              namespace: loggie-test
              deployment: apm-engine-test
              service: apm-engine-app
            fieldsFromEnv:
              podname: HOSTNAME
              service: SVC_NAME
            fieldsUnderRoot: true
        interceptors:
          - type: normalize
            name: logfile
            processors:
              - regex:
                  pattern: '(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}) (?<thread>\S+) (?<traceId>\S+) (?<spanId>\S+) (?<level>\S+)  (?<message>.*)'
        sink:
          type: elasticsearch
          hosts: ["XXXXXX:8200"]
          username: XXXXX
          password: XXXXXX
          index: "log-${fields.service}-${+YYYY.MM.DD}"
          codec:
            type: json
            beatsFormat: true
        queue:
          type: channel

其中的日志格式为：
%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{X-B3-TraceId:-}, %X{X-B3-SpanId:-}] %-5level %logger{36} -%msg%n
正则表达式为：(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}) (?<thread>\S+) (?<traceId>\S+) (?<spanId>\S+) (?<level>\S+)  (?<message>.*)  

希望将 时间，thread  level,以及message取出来，落库到ES中，如上配置不能实现，如何配置？

**Comment by ethfoo** [comment]
正则要有捕获组的命名，类似'(?<ip>\S+) (?<id>\S+) (?<u>\S+) (?<time>\[.*?\]) (?<url>\".*?\") (?<status>\S+) (?<size>\S+)'，不然没办法知道提取后具体的key是什么。
可以提取用：https://regex101.com/ 调试一下

**Comment by jackchen-2014** [comment]
> 正则要有捕获组的命名，类似'(?\S+) (?\S+) (?\S+) (?[._?]) (?"._?") (?\S+) (?\S+)'，不然没办法知道提取后具体的key是什么。 可以用：https://regex101.com/ 调试一下

上面应该语法导致展示问题，有具体的key ` (?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}) (?<thread>\S+) (?<traceId>\S+) (?<spanId>\S+) (?<level>\S+)  (?<message>.*)`  https://regex101.com/  调试也通过。
问题是下面如何提取？在哪里配置？
