### ISSUE TITLE
采集器自带时间对不上现在的时间。

### ISSUE THREAD

**Issue by jackchen-2014** [loggie-io/loggie#302]
## Ask your question here:
在sink配置中配置：
 codec:
            type: json
            beatsFormat: true
但是结果的时间戳对不上。
日志片段如下：
         "@timestamp" : "2022-07-19T11:45:35.811Z",
          "message" : "2022-07-19 19:45:30.206228 [DEBUG] mod_event_kafka.cpp:117 ************************ ",

时间差的有点远，测试环境不可能延迟这么高。

**Comment by LouisGuo** [comment]
这个怎么解决的？
