### ISSUE TITLE
删除clusterLogConig后出现bug

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [loggie-io/loggie#310]
2022-07-27 02:54:52 INF pkg/discovery/kubernetes/controller/reconcile.go:260 > clusterLogConfig: kubeevent delete event received
E0727 02:54:52.640236       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 182 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1ff1680, 0x384ff60})
	/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009f4b70})
	/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1ff1680, 0x384ff60})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/loggie-io/loggie/pkg/discovery/kubernetes/index.(*LogConfigTypeClusterIndex).GetConfig(...)
	/pkg/discovery/kubernetes/index/typecluster.go:42
github.com/loggie-io/loggie/pkg/discovery/kubernetes/index.(*LogConfigTypeClusterIndex).DeleteConfig(...)
	/pkg/discovery/kubernetes/index/typecluster.go:46
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).handleAllTypesDelete(0xc000410900, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7})
	/pkg/discovery/kubernetes/controller/reconcile.go:287 +0x158
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).reconcileClusterLogConfigDelete(0x267a540, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7})
	/pkg/discovery/kubernetes/controller/reconcile.go:261 +0xa9
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).reconcileClusterLogConfig(0xc000410900, {{0x232c7af, 0x10}, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7}})
	/pkg/discovery/kubernetes/controller/reconcile.go:51 +0x107
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).syncHandler(0xc0009f4b70, {{0x232c7af, 0x10}, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7}})
	/pkg/discovery/kubernetes/controller/controller.go:446 +0x5bb
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).processNextWorkItem.func1(0xc000410900, {0x20fb180, 0xc0009f4b70})
	/pkg/discovery/kubernetes/controller/controller.go:415 +0x212
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).processNextWorkItem(0xc000410900)
	/pkg/discovery/kubernetes/controller/controller.go:425 +0x3e
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).runWorker(...)
	/pkg/discovery/kubernetes/controller/controller.go:378
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fd0b84f8eb8)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0002b0360, {0x267a6e0, 0xc00089b380}, 0x1, 0xc00067c000)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001187b0, 0x3b9aca00, 0x0, 0x0, 0xc000118650)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0001187d0, 0x9cd446, 0xc0007f3d80)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).Run
	/pkg/discovery/kubernetes/controller/controller.go:369 +0x2af
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17cfd18]

goroutine 182 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009f4b70})
	/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1ff1680, 0x384ff60})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/loggie-io/loggie/pkg/discovery/kubernetes/index.(*LogConfigTypeClusterIndex).GetConfig(...)
	/pkg/discovery/kubernetes/index/typecluster.go:42
github.com/loggie-io/loggie/pkg/discovery/kubernetes/index.(*LogConfigTypeClusterIndex).DeleteConfig(...)
	/pkg/discovery/kubernetes/index/typecluster.go:46
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).handleAllTypesDelete(0xc000410900, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7})
	/pkg/discovery/kubernetes/controller/reconcile.go:287 +0x158
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).reconcileClusterLogConfigDelete(0x267a540, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7})
	/pkg/discovery/kubernetes/controller/reconcile.go:261 +0xa9
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).reconcileClusterLogConfig(0xc000410900, {{0x232c7af, 0x10}, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7}})
	/pkg/discovery/kubernetes/controller/reconcile.go:51 +0x107
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).syncHandler(0xc0009f4b70, {{0x232c7af, 0x10}, {0xc00080ca70, 0x9}, {0xc00080cac0, 0x7}})
	/pkg/discovery/kubernetes/controller/controller.go:446 +0x5bb
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).processNextWorkItem.func1(0xc000410900, {0x20fb180, 0xc0009f4b70})
	/pkg/discovery/kubernetes/controller/controller.go:415 +0x212
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).processNextWorkItem(0xc000410900)
	/pkg/discovery/kubernetes/controller/controller.go:425 +0x3e
github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).runWorker(...)
	/pkg/discovery/kubernetes/controller/controller.go:378
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fd0b84f8eb8)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0002b0360, {0x267a6e0, 0xc00089b380}, 0x1, 0xc00067c000)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001187b0, 0x3b9aca00, 0x0, 0x0, 0xc000118650)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0001187d0, 0x9cd446, 0xc0007f3d80)
	/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by github.com/loggie-io/loggie/pkg/discovery/kubernetes/controller.(*Controller).Run
	/pkg/discovery/kubernetes/controller/controller.go:369 +0x2a

**Comment by ethfoo** [comment]
Fixed: https://github.com/loggie-io/loggie/pull/306
