### ISSUE TITLE
关于云厂商的弹性容器实例日志采集问题

### ISSUE THREAD

**Issue by shuoshadow** [loggie-io/loggie#313]
## Ask your question here:
比如使用阿里云ack的弹性容器实例eci，运行在虚拟节点上virtual-kubelet-cn-hangzhou-xx，虚拟节点是无法部署daemonset的，而且我们业务上暂时不允许使用sidecar方式部署agent(会影响eci的规格)，这种情况有办法去采集日志吗？

**Comment by ethfoo** [comment]
这种场景貌似使用外部开源的Agent只能用sidecar的方式，如果不能用sidecar的话，我不确定eci里是否能直接用阿里云的ilogtail。
否则可以考虑代码里的日志框架直接发送到kafka等方式吧（比如log4j的kafka appender）。

**Comment by shuoshadow** [comment]
> 这种场景貌似使用外部开源的Agent只能用sidecar的方式，如果不能用sidecar的话，我不确定eci里是否能直接用阿里云的ilogtail。 否则可以考虑代码里的日志框架直接发送到kafka等方式吧（比如log4j的kafka appender）。

好的，明白了，谢谢
