### ISSUE TITLE
通过daemonset方式部署loggie，采集服务出现问题。

### ISSUE THREAD

**Issue by jackchen-2014** [loggie-io/loggie#322]
## Ask your question here:
通过 daemonset方式部署loggie到k8s集群中，采集对应的服务。如果服务所在的pod不是一个容器，有其他的sidecar容器，那么，就会出现采集不到对应的日志问题异常。如果是单独部署服务，显示正常，这种case如何处理？

**Comment by ethfoo** [comment]
带有sidecar的容器，可以在file source里增加containername参数，指定采集的容器名称。
参考：https://loggie-io.github.io/docs/reference/discovery/kubernetes/logconfig/#sources

**Comment by jackchen-2014** [comment]
增加containername如果pod有两个容器OK，如果是三个容器还是不行。
