### ISSUE TITLE
loggie在解析json格式日志包含\x时解析报错

### ISSUE THREAD

**Issue by bruse-peng** [loggie-io/loggie#332]
## Steps to Reproduce the Problem

loggie在解析json格式日志包含\x时解析报错,如下提供了一段json格式日志，关键字段脱敏了

{"@timestamp":"2022-08-18T18:23:58+08:00","@version":"1","request_body":"<xml>\x0A    <AppId><![CDATA[wx518a95ad25ddaa63]]></AppId>\x0A    <Encrypt><![CDATA[tMQcyizSKsGNYO/GiuFctrQmkve2H98MVdJ3fRxLQ6vIhj9UI0MT2Tso+GQQcIeehu8MMxMxBtckSg6XVLH0Oj8I1E49w0k0SHLeu7KuRmurwrU2Z6TaABlAQMHtdNnLXBjUEFnxx02NBXVDZy7kAjpwTsc6b+JAdDrHNixg47+X6fJ3FZ9SuC/HzvvCTW0Xx4iGWT4DVLS2iVuHH1hUCKgIl4rVpujf2PX2s7CCBmIPc6mehhpssdNS2KLTPMYtLHj2K7hmNZO63+W/8avFfOmiEqiMKKSdOvvbavHgR66ke76FRg199hIE/cvVyTh1BBPHT5Mis42j+JCquX2m0NWTEbtg4mQC2oL7DMIn1t5onov3V/qWwviziOjfFJ8BUPCDkfNDj/x4/b7Wufen/dET5OqsQ+LsRrPSWaTX8uDo3nVSXah2Y7kZM8Y8+mfj9oGuCWLzDV+yOsRUIqAWuAxxxxxxx==]]></Encrypt>\x0A</xml>\x0A","client":"100.123.3.xxx","source_client":"81.69.101.xxx","client_realip":"81.69.101.xxx","r":"third-auth/get-message","url":"/index.php","status": "200","upstream_response_time": "0.018","domain":"xxxxxx","host":"192.168.4.195","size":17,"responsetime":0.018,"request_method": "POST", "request": "POST /index.php?r=third-auth/get-message&signature=b7833036133f99f1b77dc9df6b2de23d752158ce&timestamp=1660818238&nonce=1518663836&encrypt_type=aes&msg_signature=b77207b802b8c3be80cd07f74cf82d066bcfc229 HTTP/1.1", "referer": "-","response_header": "-","ua": "Mozilla/4.0"}

**Comment by ethfoo** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3616466/220504330-1765ba6d-3b49-4ce0-af18-4d9429f37a81.png">

https://jsonlint.com/

This JSON in particular shows as invalid.
JSON cannot contains x0A or \n.
