### ISSUE TITLE
二进制下载找不到文件啊

### ISSUE THREAD

**Issue by charles-liming** [loggie-io/loggie#364]
https://loggie-io.github.io/docs/getting-started/install/node/  里边的下载链接，1.3.0 1.2.4  尝试拼接了2个版本，否是404 ，进入github 的release 页面，也没有二进制包，

**Comment by charles-liming** [comment]
使用了docker cp 给搞了一份，这个有点尴尬啊

**Comment by charles-liming** [comment]
还是希望文档更加专业一些。

**Comment by ethfoo** [comment]
v1.3.0版本还没正式发布哈，目前只发布了v1.3.0-rc.0，rc版本暂时没有提供二进制的release
