### ISSUE TITLE
loggie 无法收集kube-event信息

### ISSUE THREAD

**Issue by Michael754267513** [loggie-io/loggie#388]
## Ask your question here:
版本：loggie-v1.3.0-rc.0
采用inclusterconfig 读取配置文件

配置如下

---
apiVersion: loggie.io/v1beta1
kind: Interceptor
metadata:
  name: jsondecode
spec:
  interceptors: |
    - type: normalize
      name: json
      processors:
      - jsonDecode: ~
      - drop:
          targets: ["body"]
---
apiVersion: loggie.io/v1beta1
kind: ClusterLogConfig
metadata:
  name: kubeevent
spec:
  selector:
    type: cluster
    cluster: aggregator
  pipeline:
    sources: |
      - type: kubeEvent
        name: event
    interceptorRef: jsondecode
    sinkRef: k8sbgy-kube-eventer

无法收集kube-event信息

**Comment by ethfoo** [comment]
Loggie本身的日志看下？
或者先尝试去掉interceptor，使用sink dev来排查一下？
也可以加微信群讨论：https://loggie-io.github.io/docs/getting-started/overview/#_3

**Comment by Michael754267513** [comment]
aggregator:
  enabled: true

问题解决，在helm文件里面，开启聚合，会以sts的形式部署， 不开启，还是会以ds的形式部署，无法在kube-system看到lease，测试版本1.3

**Comment by Michael754267513** [comment]
感谢 @ethfoo 耐心指导
