### ISSUE TITLE
请问下，kafka支持版本？

### ISSUE THREAD

**Issue by vinsonzou** [loggie-io/loggie#444]
是否支持kafka 3.x版本？

**Comment by ethfoo** [comment]
当前v1.4.0-rc.0有两种kafka sink：
- kafka sink
   使用的client是github.com/segmentio/kafka-go v0.4.23
  > kafka-go is currently compatible with Kafka versions from 0.10.1.0 to 2.1.0. While latest versions will be working, some features available from the Kafka API may not be implemented yet.

- franzKafka sink
    使用的client是github.com/twmb/franz-go v1.10.4
    > Feature complete client (Kafka >= 0.8.0 through v3.2+)
