### ISSUE TITLE
topic(component) has no consumer listener

### ISSUE THREAD

**Issue by wyfaq** [loggie-io/loggie#492]
## Ask your question here:
sink to kafka, debug 日志显示：
topic(queue) has no consumer listener
topic(component) has no consumer listener

pipeline配置：
pipelines:
  - name: demo
    sources:
      - type: file
        name: access
        paths:
          - "/tmp/pcd-scloud-svc/scloud-svc_accesslog_VM_192_centos.log"
    sink:
      type: franzKafka
      brokers:
        - "192.101.241.101:9092"
        - "192.101.241.102:9092"
        - "192.101.241.103:9092"
      topic: "pcd-scloud-svc"

loggie为最新的1.4.0

kafka可用，有没有consumer不应该影响日志推送的吧？

**Comment by ethfoo** [comment]
debug日志不影响，只是你没配置这两个listener导致的

**Comment by wyfaq** [comment]
但是对应topic也没有创建成功
