### ISSUE TITLE
希望推送消息到kafka

### ISSUE THREAD

**Issue by shuidai** [loggie-io/loggie#497]
sink配置如下

`cat << EOF | kubectl apply -f -
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  name: kafka
spec:
  sink: |
    type: kafka
    brokers: ["10.10.x.x:9092"]
    topic: "hello"
EOF`
lgc配置如下
`cat << EOF | kubectl apply -f -
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: stdout
  namespace: kube-system
spec:
  pipeline:
    sinkRef: kafka
    sources: |
      - type: file
        name: stdout
        paths:
          - stdout
  selector:
    type: pod
    labelSelector:
      k8s-app: calico-node
EOF`

通过查看lgc的describe,是成功获取到消息的，但是不能将消息发送到kafka，请帮我看看是什么情况
环境信息：k8s v1.24.8
loggie版本：v1.4.0-rc.0
kafka状态正常。

**Comment by ethfoo** [comment]
有可能是kafka的topic关闭了自动创建，导致阻塞住。
也可以尝试使用新版的kafka库：https://loggie-io.github.io/docs/reference/pipelines/sink/franzkafka/

**Comment by shuidai** [comment]
好的，谢谢
通过设置如下kafka的参数，允许自动创建topic，kafka已经能成功获取到消息了
auto.create.topics.enable=true
