### ISSUE TITLE
RoadMap 2023?

### ISSUE THREAD

**Issue by Max-Cheng** [loggie-io/loggie#498]
## In what area(s)?
/area Project

## Ask your question here:
More Detail about 2023 Project Roadmap?

**Comment by ethfoo** [comment]
Refer to: https://loggie-io.github.io/docs/getting-started/roadmap/roadmap-2023/

I don't know which one of the details you want to know.

**Comment by Max-Cheng** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/21263915/225526624-f1d9fd41-dc44-487e-85e8-29bd72de6841.png">
Github Project still 2022 Project, it's weird
