### ISSUE TITLE
经常出现最新日志无法采集(containerd无挂载模式）

### ISSUE THREAD

**Issue by quchwe** [loggie-io/loggie#500]
日志采着采着就不采集了，即使是新文件也不行。查看loggie dashboard，offset为0
1. pipeline配置如下：
![pipeline](https://user-images.githubusercontent.com/17445015/226230456-b32e21a9-5aeb-494d-8143-4cbec003bfb3.png)

2. loggie日志
![log](https://user-images.githubusercontent.com/17445015/226230506-902c0eff-b8ce-4747-8d78-4cddb0b10a82.png)

3. 日志文件路径
  
![dirs](https://user-images.githubusercontent.com/17445015/226230567-42ea960b-83a0-40ba-9dfc-04e829c8974d.png)

4. loggie inspect
![inspect](https://user-images.githubusercontent.com/17445015/226230669-c6501777-9faf-49e7-bdb2-f8534a946bc0.png)

**Comment by quchwe** [comment]
loggie版本：loggieio/loggie:v1.4.0

**Comment by ethfoo** [comment]
请问是使用的containerd容器运行时，并且无挂载volume的方式去采集日志吗？

**Comment by quchwe** [comment]
> 请问是使用的containerd容器运行时，并且无挂载volume的方式去采集日志吗？
> 
> 如果使用emptyDir挂载容器日志，会有该问题吗？

是用的containerd, 无挂载volume方式采集。empty dir我测试下。主机各组件版本：
![image](https://user-images.githubusercontent.com/17445015/226264650-7c497bd3-0ff4-41a3-a922-ebc185357490.png)

**Comment by quchwe** [comment]
> 果使用emptyDir挂载容器日志，会有该问题吗？
使用emptyDir，loggie容器内，pipeline和文件如下：
![loggie](https://user-images.githubusercontent.com/17445015/227084287-e87aa631-5322-4aec-b2d3-4ae26d878656.png)

loggie日志：
![image](https://user-images.githubusercontent.com/17445015/227084451-ed9ac211-5291-4fa5-89ec-6253011faf0a.png)
[loggie.log](https://github.com/loggie-io/loggie/files/11046355/loggie.log)

采集状态：
![image](https://user-images.githubusercontent.com/17445015/227084979-10cbb0bd-e68a-4458-b143-63a48bcf192b.png)

![image](https://user-images.githubusercontent.com/17445015/227084952-cc221c20-20e3-4674-90bb-a8b47c9956a1.png

loggie inspect: 
![image](https://user-images.githubusercontent.com/17445015/227085529-b78be65b-ea2f-4215-b8a0-f1c4b48d6f7d.png)

容器内文件内容：
![image](https://user-images.githubusercontent.com/17445015/227085282-78867411-dff9-4d4c-8e52-41249a2a6d1a.png)

有个问题就是我的core文件是个软链接，这样配置有什么问题吗? 还是没有采集的

**Comment by ethfoo** [comment]
emptyDir等挂载的方式都没有问题，软连接的一般也没有问题（除非链接的文件在loggie容器内不能识别，比如链接到了文件/data/a.log，但是loggie pod没有挂载/data路径）

看起来你的这个是配置存在冲突导致reload失败，建议重启一下Loggie再观察一下。

**Comment by quchwe** [comment]
> emptyDir等挂载的方式都没有问题，软连接的一般也没有问题（除非链接的文件在loggie容器内不能识别，比如链接到了文件/data/a.log，但是loggie pod没有挂载/data路径）
> 
> 看起来你的这个是配置存在冲突导致reload失败，建议重启一下Loggie再观察一下。

配置存在冲突？loggie重启就会收集，就是收着收着会停止，我另一个服务，做的volume挂载到主机，跑了一段时间后，新的日志文件不监听。我再验证一下看看

**Comment by ixiaoyi93** [comment]
> 

我也遇到了，测试了一下。不敢上生产啊。。。

**Comment by ethfoo** [comment]
@ixiaoyi93 微信群里交流下，发一下日志看看，loggie当前确实没有在containerd无挂载volume的场景生产大规模跑过，一起看下怎么解决这个问题
