### ISSUE TITLE
是否支持centos6

### ISSUE THREAD

**Issue by Abelcray** [loggie-io/loggie#502]
## Ask your question here:  想打包一个centos6版本的，是否支持，求编译方法

**Comment by ethfoo** [comment]
如果是主机部署，centos6的c lib库版本较低，loggie使用的持久化sqlite3不兼容。
不过最新的main分支已经提供了另外的一种持久化引擎badger适配，但需要重新构建，请参考makefile中build-no-sqlite命令。

**Comment by Abelcray** [comment]
好的，感谢

**Comment by laojianzi** [comment]
也可以尝试使用 gcc 4.8 编译，这是我折腾的一些简单记录可以参考一下: https://blog.0xbb.dev/posts/cgo-kernel-too-old/
