### ISSUE TITLE
关于容器采集的疑问？

### ISSUE THREAD

**Issue by aivinray** [loggie-io/loggie#535]
## In what area(s)?
> /area discovery

## Ask your question here:
看文档，loggie是采用list watch的方式监听容器的事件。想请教两个问题：
1. 请问这种方式是否对api server造成比较大的压力？
2. 每个采集器都会收到集群内所有的pod变化，那对每个pod都会生成一个采集配置吗？最终又是如何过滤出只针对本宿主机的容器进行采集的呢？

**Comment by ethfoo** [comment]
loggie只会监听自身所在节点的pod的事件，并不会list&watch所有的pod变化。
只有logconfig/clusterlogconfig匹配到所在节点的pod，才会生成相应的配置。

**Comment by aivinray** [comment]
> loggie只会监听自身所在节点的pod的事件，并不会list&watch所有的pod变化。 只有logconfig/clusterlogconfig匹配到所在节点的pod，才会生成相应的配置。

我对kubeinformers的包不是特别熟悉，能告诉一下大致的代码路径，是怎么只监听自身所在节点的pod事件的吗？

**Comment by ethfoo** [comment]
https://github.com/loggie-io/loggie/blob/main/pkg/discovery/kubernetes/kubernetes.go#LL114C2-L114C21
