### ISSUE TITLE
Loki return 413 Request Entity Too Large

### ISSUE THREAD

**Issue by liyongxian** [loggie-io/loggie#609]
## What version of Loggie?
**v1.4.1**
## Expected Behavior

Log of  loggie Pod ： **returned HTTP status 413 Request Entity Too Large**
![image](https://github.com/loggie-io/loggie/assets/18571576/3110ec2e-ad91-41bb-9287-cd8b3fcb2258)

**loggie config.yaml:**
![image](https://github.com/loggie-io/loggie/assets/18571576/614ab10f-2c7f-4de5-b9e5-ea43f4385ae6)

**Sink**
![image](https://github.com/loggie-io/loggie/assets/18571576/f9c2ca0b-9b0b-436b-9f3d-9a8199900a2a)

**Interceptor**
![image](https://github.com/loggie-io/loggie/assets/18571576/ebeb99a2-0f19-409f-bae1-9c25a2801c36)

**LogConfig**

![image](https://github.com/loggie-io/loggie/assets/18571576/a78dd95a-e93a-413a-8517-527bb552c3a7)

Thanks.

**Comment by ethfoo** [comment]
Maxbytes interceptor can only limit the length of a single log. When a log is sent to Loki, it is aggregated into batch in the queue first. loki returns 413 because the whole batch is too large. You can try to reduce the aggregated batch size.
Reference:
https://loggie-io.github.io/docs/main/reference/pipelines/queue/channel/

**Comment by liyongxian** [comment]
Thanks for your reply.
 How to set the aggregated batch size? 
Thanks.

**Comment by ethfoo** [comment]
The queue is added by default, you can configure the queue in the defaults of configmap, https://github.com/loggie-io/loggie/blob/main/loggie.yml#L31
Try reducing both batchSize and batchBytes to half, for overriding the default.

**Comment by liyongxian** [comment]
It does not work.
**loggie.yml.**

![image](https://github.com/loggie-io/loggie/assets/18571576/fbda6de2-f4ba-4344-8d56-6af177bb72b4)

**loggie log.**

![image](https://github.com/loggie-io/loggie/assets/18571576/2f606586-3ded-4a35-bc50-bd2904606642)

![image](https://github.com/loggie-io/loggie/assets/18571576/29c155d2-593f-43de-be9a-99307330a85d)

**Comment by liyongxian** [comment]
I test several times,when more logs sink to loki,the loggie has the problems.

**Comment by liyongxian** [comment]
@ethfoo Please mark bug.

**Comment by ethfoo** [comment]
Your configuration is misplaced, it should be in the `defaults`, not in the `monitor`.

eg: 
```
  defaults:
    queue:
      type: channel
      batchSize: 100
      batchBytes: 3355443
```
