### ISSUE TITLE
ackOffset is larger than file size(9204).is inode repeat

### ISSUE THREAD

**Issue by liyongxian** [loggie-io/loggie#611]
## What version of Loggie?
v1.4.1
## Expected Behavior

![image](https://github.com/loggie-io/loggie/assets/18571576/e11e597f-e133-4472-8b7e-7ad2c1d01005)
How to set ackOffset? Thanks.

**Comment by ethfoo** [comment]
This may be caused by repeated inodes, and the printed log does not actually affect the collection.
It is recommended to use the latest v1.5 version, which has some optimizations for this scene.
