### ISSUE TITLE
一个pod内采集容器日志出现重复!

### ISSUE THREAD

**Issue by guanxingfeng** [loggie-io/loggie#628]
## What version of Loggie?
v1.4.0
![image](https://github.com/loggie-io/loggie/assets/25924966/18236eb3-e8fd-4857-a81c-17ce8b4bcbc2)

## Expected Behavior
配置好pod日志采集后，查询es日志发现重复日志，不知什么原因？
原始pod日志如下：
![image](https://github.com/loggie-io/loggie/assets/25924966/215a1952-ecab-439c-89df-e74097b2a55b)

在es查询日志出现重复的两条：
![1693474117664](https://github.com/loggie-io/loggie/assets/25924966/44ec4b39-f73d-43c2-ab62-4103cdbecc1b)

配置如下：
`
root@public-safety-test:~/lyx/loggie# kubectl get logconfigs.loggie.io -n infra-mgr log-test -oyaml
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  generation: 2
  name: log-test
  namespace: infra-mgr
  resourceVersion: "650936107"
  selfLink: /apis/loggie.io/v1beta1/namespaces/infra-mgr/logconfigs/log-test
  uid: 5d73274f-ef39-468e-8d1f-6e42217135a2
spec:
  pipeline:
    sinkRef: sink-es-pod
    sources: |
      - addonMeta: true
        name: common
        paths:
        - stdout
        type: file
  selector:
    labelSelector:
      app: holli-edge-console-console
    type: pod

root@public-safety-test:~/lyx/loggie# kubectl get sinks.loggie.io sink-es-pod -oyaml
...
  name: sink-es-pod
  resourceVersion: "644621225"
  selfLink: /apis/loggie.io/v1beta1/sinks/sink-es-pod
  uid: 636b2142-9efb-4e50-b3f0-bcf703b4b1a9
spec:
  sink: |
    type: elasticsearch
    hosts:
    - "elasticsearch-cluster-es-http.monitoring:9200"
    username: elastic
    password: 79x4TZ2b411Eql0wd9SzPNx0
    index: "${fields.workloadname}-${fields.namespace}-logconfig-${+YYYY.MM.DD}"
    etype: "doc"
    codec:
      type: json
      beatsFormat: true

`

**Comment by ethfoo** [comment]
这个时间点，对Loggie有什么操作吗？或者修改了配置导致reload之类的？

**Comment by guanxingfeng** [comment]
已解决，不是软件问题，是环境问题，同一个节点上其他人又部署了一个loggie程序导致。
![5KKPSMAN6}0`_L`J)BCY6XA](https://github.com/loggie-io/loggie/assets/25924966/a69780e8-73e9-4f75-847e-50f556290dec)
