### ISSUE TITLE
怎么考虑pipelines之间的资源隔离问题的？

### ISSUE THREAD

**Issue by carrotshub** [loggie-io/loggie#90]
你好，developer~
loggie以sidecar 或者 daemonSet的方式部署后，对loggie容器限制一定的资源，那么不同的pipeline之间就会竞争资源，如果某个数据量增大，必然会影响其它pipeline的采集状态。请问在设计上对于这块是怎么考虑的？谢谢~

**Comment by mmaxiaolei** [comment]
对于公共组件来说：比如watcher、reader来说，都是采用事件模式，每个pipeline的工作任务都会分配相对固定的执行时间片，以使得不同pipeline的工作任务得到均匀的执行。因此不存在相互影响

对于pipeline独立的组件来说，限制方式有多种：
1. 默认限制：每个pipeline有个独立的event对象池，可用event数量是固定为(queue的batchSize)*(sink并行度+1)，因此数据量再大也不会突破这个数量
2. 手动配置：可以配置限流(limit)interceptor，限制pipeline的数据采集速率

**Comment by carrotshub** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我将尽快回复！谢谢！

**Comment by carrotshub** [comment]
> 1. 默认限制：每个pipeline有个独立的event对象池，可用event数量是固定为(queue的batchSize)*(sink并行度+1)，因此数据量再大也不会突破这个数量

感谢你的回复，对pipeline通过限制queue的大小确实是一个解决思路，但是在单个event大小过大的场景下依然会导致该pipeline占用资源过高（memSize=(queue的batchSize)*(sink并行度+1)*(单条event大小)），导致OOM问题。那么loggie目前是否有对采集event大小的限制？

**Comment by mmaxiaolei** [comment]
默认的channel queue的chan size其实只有16。source采集的快，需要sink端能匹配发送速度，不然还是会被阻塞。
如果是考虑到单个event过大导致的oom的问题，默认event的body限制最大是128K，batchSize是2048，因此pipeline的内存会被限制在256M*sink并行度

**Comment by carrotshub** [comment]
好的，明白了，感谢~ 对这个项目比较感兴趣，有没有交流群便于大家深入讨论？

**Comment by mmaxiaolei** [comment]
https://loggie-io.github.io/docs/getting-started/overview/#_3
可以扫链接里面的二维码加微信群

**Comment by carrotshub** [comment]
建议这个二维码给项目README也放一个
