### ISSUE TITLE
针对与一个pod多个container的问题

### ISSUE THREAD

**Issue by BruceChinese** [loggie-io/loggie#94]
针对与一个pod多个container的问题，如果收集的是file文件日志，对于每个container都有要收集的日志，这个怎么定义

**Comment by ethfoo** [comment]
fie source里可以填containerName和excludeContainerPatterns，一般一个container对应一个source。
参考一下这里：https://loggie-io.github.io/docs/reference/discovery/kubernetes/logconfig/#sources

**Comment by BruceChinese** [comment]
好的 谢谢
