### ISSUE TITLE
upgrade client go version to 0.22.2 and fix int type error 

### ISSUE THREAD

**Issue by fengshunli** [loggie-io/loggie#97]
fix client-go v0.19.8 vuln
![image](https://user-images.githubusercontent.com/18587688/158288858-d9b9fff7-b84f-4f59-a063-e5f7f85d3e23.png)

fix job  int type error 
![image](https://user-images.githubusercontent.com/18587688/158288963-9c7a0861-ea9d-4831-823f-6ace2a571840.png)

my submitted pr https://github.com/loggie-io/loggie/pull/99

**Comment by ethfoo** [comment]
//merged
