### ISSUE TITLE
loggie文章编辑整理也是需要时间的，如果在datafun之外投稿转发的话也麻烦带一下编辑整理

### ISSUE THREAD

**Issue by tbbrave** [loggie-io/loggie#98]
请尊重一下志愿者劳动。

**Comment by tbbrave** [comment]
https://mp.weixin.qq.com/s/jz0b5TSgGvqfswhX9lKcyg比如这篇，麻烦注意。

**Comment by ethfoo** [comment]
实在不好意思，这篇其他公众号的转推，我本人并不知情，请微信联系一下loggie bot

**Comment by ethfoo** [comment]
已经联系相关公众号添加

**Comment by ethfoo** [comment]
我发了一封邮件给您邮箱了，请查收，再次表示抱歉。
另外我们自己的文章都已修改，带上您的编辑整理。

**Comment by tbbrave** [comment]
好的。这边云原生社区反馈过来说是他们转载时候就没有我作为志愿者编辑整理的信息，我当然希望能够在开源过程中一方面享受参与开源带来的乐趣也一方面志愿者工作可以被尊重和认可。

**Comment by tbbrave** [comment]
我看到云原生社区已经加好了。thx。
